--liquibase formatted sql
--changeSet Slawek84PL:002

CREATE TABLE IF NOT EXISTS games
(
    game_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255),
    description         VARCHAR(255),
    game_tags           VARCHAR(255),
    game_service_link   VARCHAR(255),
    source_code_link    VARCHAR(255),
    moderation_status   VARCHAR(50),
    max_players         INTEGER,
    times_played_total  BIGINT,
    release_date        DATE,
    last_time_played    TIMESTAMP,
    author_id           INTEGER,
    CONSTRAINT pk_games PRIMARY KEY (game_id),
    CONSTRAINT fk_games_author FOREIGN KEY (author_id) REFERENCES users(user_id)
);