--liquibase formatted sql
--changeSet Slawek84PL:003

CREATE TABLE IF NOT EXISTS game_rating
(
    rating_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id     INTEGER,
    user_id     INTEGER,
    score       INTEGER,
    comment     VARCHAR(255),
    posting_date DATE,
    CONSTRAINT pk_game_rating PRIMARY KEY (rating_id),
    CONSTRAINT fk_game_rating_game FOREIGN KEY (game_id) REFERENCES games(game_id),
    CONSTRAINT fk_game_rating_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT uc_game_rating UNIQUE (game_id, user_id)
);