--liquibase formatted sql
--changeSet Slawek84PL:003

CREATE TABLE IF NOT EXISTS game_rating
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score        INTEGER                                 NOT NULL,
    comment      VARCHAR(255),
    posting_date date,
    game_id      BIGINT,
    CONSTRAINT pk_game_rating PRIMARY KEY (id)
);

ALTER TABLE game_rating
    ADD CONSTRAINT FK_GAME_RATING_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);