--liquibase formatted sql
--changeSet Slawek84PL:004

CREATE TABLE IF NOT EXISTS game_active
(
    active_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id     INTEGER,
    user_id     INTEGER,
    current_players INTEGER,
    started_at  TIMESTAMP,
    CONSTRAINT pk_game_active PRIMARY KEY (active_id),
    CONSTRAINT fk_game_active_game FOREIGN KEY (game_id) REFERENCES games(game_id),
    CONSTRAINT fk_game_active_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);