spring:
  application:
    name: MAIN-SERVICE
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

gaminatorium:
  openapi:
    local-url: http://localhost:8080
    prod-url: https://gaminatorium.eu
