--liquibase formatted sql

--changeSet Slawek84PL:002_1
CREATE TABLE IF NOT EXISTS users
(
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);

--changeSet Slawek84PL:002_2
INSERT INTO users (user_name, email, password)
VALUES ('user', 'user@gaminatorium.eu', 'pass'),
       ('admin', 'admin@gaminatorium.eu', 'pass'),
       ('Rick', 'rick@gaminatorium.eu', 'pass');